attention_head_size: 4
categorical_groups: &id004 {}
causal_attention: true
dataset_parameters:
  add_encoder_length: false
  add_relative_time_idx: false
  add_target_scales: false
  allow_missing_timesteps: false
  categorical_encoders:
    __group_id__group: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
      add_nan: false
      classes_:
        ? !!python/object/apply:numpy.core.multiarray.scalar
        - &id001 !!python/object/apply:numpy.dtype
          args:
          - i8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - !!binary |
          AQAAAAAAAAA=
        : 0
      classes_vector_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - &id002 !!python/name:numpy.ndarray ''
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id001
        - false
        - !!binary |
          AQAAAAAAAAA=
      warn: true
  constant_fill_strategy: {}
  group_ids:
  - group
  lags: {}
  max_encoder_length: 30
  max_prediction_length: 10
  min_encoder_length: 30
  min_prediction_idx: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    AAAAAAAAAAA=
  min_prediction_length: 10
  predict_mode: false
  randomize_length: null
  scalers:
    time_varying_feature: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.5.0
      copy: true
      feature_names_in_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - !!python/object/apply:numpy.dtype
          args:
          - O8
          - false
          - true
          state: !!python/tuple
          - 3
          - '|'
          - null
          - null
          - null
          - -1
          - -1
          - 63
        - false
        - - time_varying_feature
      mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - &id003 !!python/object/apply:numpy.dtype
          args:
          - f8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - false
        - !!binary |
          rkfhehSu7z8=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        ZAAAAAAAAAA=
      scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          KvTuyPAw6j8=
      var_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          juTyH9Jv5T8=
      with_mean: true
      with_std: true
  static_categoricals: &id006 []
  static_reals: &id007 []
  target: target
  target_normalizer: &id005 !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
    add_nan: false
    classes_:
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAAAAAAAA=
      : 0
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        AgAAAAAAAAA=
      : 1
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        BAAAAAAAAAA=
      : 2
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        BQAAAAAAAAA=
      : 3
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        BgAAAAAAAAA=
      : 4
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        BwAAAAAAAAA=
      : 5
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        CAAAAAAAAAA=
      : 6
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        CQAAAAAAAAA=
      : 7
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        CgAAAAAAAAA=
      : 8
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        CwAAAAAAAAA=
      : 9
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        DAAAAAAAAAA=
      : 10
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        DQAAAAAAAAA=
      : 11
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        DgAAAAAAAAA=
      : 12
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        DwAAAAAAAAA=
      : 13
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        EAAAAAAAAAA=
      : 14
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        EQAAAAAAAAA=
      : 15
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        EgAAAAAAAAA=
      : 16
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        EwAAAAAAAAA=
      : 17
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        FAAAAAAAAAA=
      : 18
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        FQAAAAAAAAA=
      : 19
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        FgAAAAAAAAA=
      : 20
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        FwAAAAAAAAA=
      : 21
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        GAAAAAAAAAA=
      : 22
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        GQAAAAAAAAA=
      : 23
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        GgAAAAAAAAA=
      : 24
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        GwAAAAAAAAA=
      : 25
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        HAAAAAAAAAA=
      : 26
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        HQAAAAAAAAA=
      : 27
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        HgAAAAAAAAA=
      : 28
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        HwAAAAAAAAA=
      : 29
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        IAAAAAAAAAA=
      : 30
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        IQAAAAAAAAA=
      : 31
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        IgAAAAAAAAA=
      : 32
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        IwAAAAAAAAA=
      : 33
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        JAAAAAAAAAA=
      : 34
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        JQAAAAAAAAA=
      : 35
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        JgAAAAAAAAA=
      : 36
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        JwAAAAAAAAA=
      : 37
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        KAAAAAAAAAA=
      : 38
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        KQAAAAAAAAA=
      : 39
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        KgAAAAAAAAA=
      : 40
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        KwAAAAAAAAA=
      : 41
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        LAAAAAAAAAA=
      : 42
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        LQAAAAAAAAA=
      : 43
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        LgAAAAAAAAA=
      : 44
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        LwAAAAAAAAA=
      : 45
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        MAAAAAAAAAA=
      : 46
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        MQAAAAAAAAA=
      : 47
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        MgAAAAAAAAA=
      : 48
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        MwAAAAAAAAA=
      : 49
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        NAAAAAAAAAA=
      : 50
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        NQAAAAAAAAA=
      : 51
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        NgAAAAAAAAA=
      : 52
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        NwAAAAAAAAA=
      : 53
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        OAAAAAAAAAA=
      : 54
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        OQAAAAAAAAA=
      : 55
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        OgAAAAAAAAA=
      : 56
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        OwAAAAAAAAA=
      : 57
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        PAAAAAAAAAA=
      : 58
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        PQAAAAAAAAA=
      : 59
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        PgAAAAAAAAA=
      : 60
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        PwAAAAAAAAA=
      : 61
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        QAAAAAAAAAA=
      : 62
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        QQAAAAAAAAA=
      : 63
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        QgAAAAAAAAA=
      : 64
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        QwAAAAAAAAA=
      : 65
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        RAAAAAAAAAA=
      : 66
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        RQAAAAAAAAA=
      : 67
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        RgAAAAAAAAA=
      : 68
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        RwAAAAAAAAA=
      : 69
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        SAAAAAAAAAA=
      : 70
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        SQAAAAAAAAA=
      : 71
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        SgAAAAAAAAA=
      : 72
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        SwAAAAAAAAA=
      : 73
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        TAAAAAAAAAA=
      : 74
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        TQAAAAAAAAA=
      : 75
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        TgAAAAAAAAA=
      : 76
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        TwAAAAAAAAA=
      : 77
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        UAAAAAAAAAA=
      : 78
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        UQAAAAAAAAA=
      : 79
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        UgAAAAAAAAA=
      : 80
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        UwAAAAAAAAA=
      : 81
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        VAAAAAAAAAA=
      : 82
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        VQAAAAAAAAA=
      : 83
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        VgAAAAAAAAA=
      : 84
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        VwAAAAAAAAA=
      : 85
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        WAAAAAAAAAA=
      : 86
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        WQAAAAAAAAA=
      : 87
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        WgAAAAAAAAA=
      : 88
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        WwAAAAAAAAA=
      : 89
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        XAAAAAAAAAA=
      : 90
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        XQAAAAAAAAA=
      : 91
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        XgAAAAAAAAA=
      : 92
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        XwAAAAAAAAA=
      : 93
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        YAAAAAAAAAA=
      : 94
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        YQAAAAAAAAA=
      : 95
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        YgAAAAAAAAA=
      : 96
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        YwAAAAAAAAA=
      : 97
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        ZQAAAAAAAAA=
      : 98
      ? !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        ZwAAAAAAAAA=
      : 99
    classes_vector_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple
        - 100
      - *id001
      - false
      - !!binary |
        AAAAAAAAAAACAAAAAAAAAAQAAAAAAAAABQAAAAAAAAAGAAAAAAAAAAcAAAAAAAAACAAAAAAAAAAJ
        AAAAAAAAAAoAAAAAAAAACwAAAAAAAAAMAAAAAAAAAA0AAAAAAAAADgAAAAAAAAAPAAAAAAAAABAA
        AAAAAAAAEQAAAAAAAAASAAAAAAAAABMAAAAAAAAAFAAAAAAAAAAVAAAAAAAAABYAAAAAAAAAFwAA
        AAAAAAAYAAAAAAAAABkAAAAAAAAAGgAAAAAAAAAbAAAAAAAAABwAAAAAAAAAHQAAAAAAAAAeAAAA
        AAAAAB8AAAAAAAAAIAAAAAAAAAAhAAAAAAAAACIAAAAAAAAAIwAAAAAAAAAkAAAAAAAAACUAAAAA
        AAAAJgAAAAAAAAAnAAAAAAAAACgAAAAAAAAAKQAAAAAAAAAqAAAAAAAAACsAAAAAAAAALAAAAAAA
        AAAtAAAAAAAAAC4AAAAAAAAALwAAAAAAAAAwAAAAAAAAADEAAAAAAAAAMgAAAAAAAAAzAAAAAAAA
        ADQAAAAAAAAANQAAAAAAAAA2AAAAAAAAADcAAAAAAAAAOAAAAAAAAAA5AAAAAAAAADoAAAAAAAAA
        OwAAAAAAAAA8AAAAAAAAAD0AAAAAAAAAPgAAAAAAAAA/AAAAAAAAAEAAAAAAAAAAQQAAAAAAAABC
        AAAAAAAAAEMAAAAAAAAARAAAAAAAAABFAAAAAAAAAEYAAAAAAAAARwAAAAAAAABIAAAAAAAAAEkA
        AAAAAAAASgAAAAAAAABLAAAAAAAAAEwAAAAAAAAATQAAAAAAAABOAAAAAAAAAE8AAAAAAAAAUAAA
        AAAAAABRAAAAAAAAAFIAAAAAAAAAUwAAAAAAAABUAAAAAAAAAFUAAAAAAAAAVgAAAAAAAABXAAAA
        AAAAAFgAAAAAAAAAWQAAAAAAAABaAAAAAAAAAFsAAAAAAAAAXAAAAAAAAABdAAAAAAAAAF4AAAAA
        AAAAXwAAAAAAAABgAAAAAAAAAGEAAAAAAAAAYgAAAAAAAABjAAAAAAAAAGUAAAAAAAAAZwAAAAAA
        AAA=
    warn: true
  time_idx: time_idx
  time_varying_known_categoricals: &id008 []
  time_varying_known_reals: &id009
  - time_varying_feature
  time_varying_unknown_categoricals: []
  time_varying_unknown_reals:
  - target
  variable_groups: *id004
  weight: null
dropout: 0.1
embedding_labels: {}
embedding_paddings: []
embedding_sizes: {}
hidden_continuous_size: 16
hidden_continuous_sizes: {}
hidden_size: 32
learning_rate: 0.03
log_gradient_flow: false
log_interval: 10
log_val_interval: null
lstm_layers: 1
max_encoder_length: 30
monotone_constaints: {}
optimizer: adam
optimizer_params: null
output_size: 7
output_transformer: *id005
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 4
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals: *id006
static_reals: *id007
time_varying_categoricals_decoder: *id008
time_varying_categoricals_encoder: []
time_varying_reals_decoder: *id009
time_varying_reals_encoder:
- time_varying_feature
- target
weight_decay: 0.0
x_categoricals: []
x_reals:
- time_varying_feature
- target
